Training...
Epoch 0
Training Iterations:   0%|                                                                                                                                                                                                                                                               | 0/40 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/user/as6154/dissert/gpt2.py", line 173, in <module>
    output = model(input_seq)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/dissert/gpt2.py", line 89, in forward
    output = self._backbone(inputs_embeds=embeds).last_hidden_state
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1235, in forward
    outputs = block(
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 720, in forward
    attn_outputs = self.attn(
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 623, in forward
    query, key, value = self.c_attn(hidden_states).split(self.split_size, dim=2)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/pytorch_utils.py", line 104, in forward
    x = torch.addmm(self.bias, x.view(-1, x.size(-1)), self.weight)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 142.00 MiB. GPU  has a total capacity of 79.14 GiB of which 87.19 MiB is free. Process 569849 has 59.29 GiB memory in use. Including non-PyTorch memory, this process has 19.74 GiB memory in use. Of the allocated memory 19.20 GiB is allocated by PyTorch, and 57.71 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)